server:
  port: 21100

spring:
  application:
    name: jwt-auth-service
  redis:
    database: 0
    host: 192.168.175.100
    port: 6379
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
