server:
  port: 21100

spring:
  application:
    name: jwt-auth-service
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false