server:
  port: 21200

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.210.56:3306/abc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 19971124

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/